# Generated by Django 3.2.11 on 2024-02-17 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_post_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default='AI', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='app.category'),
        ),
    ]
