# Generated by Django 3.2.11 on 2024-02-23 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(choices=[('admin', 'admin'), ('ruk', 'Rukevwe Omoro')], default='admin', max_length=50),
        ),
    ]
