# Generated by Django 3.2.11 on 2024-03-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_alt_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
