# Generated by Django 3.2.11 on 2024-03-09 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_post_image_alt_text'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('title', 'slug')},
        ),
    ]
