# Generated by Django 3.2.11 on 2024-03-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_post_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(choices=[('admin', 'admin'), ('Rukevwe Omoro', 'Ruk')], default='admin', max_length=50),
        ),
    ]
